### ISSUE TITLE
CalledProcessError

### ISSUE THREAD

**Issue by frankV** [lincolnloop/salmon#25]
Followed basic instructions and got the following error when running `salmon run_checks`:

`CalledProcessError: Command '['/usr/bin/python', '/usr/bin/salt', '--static', '--out=json', '192.168.1.100', 'service.status', 'nginx']' returned non-zero exit status 2`

(ip address was changed)
Any ideas? Maybe I did something wrong in the setup.

**Comment by ipmb** [comment]
If you run `/usr/bin/python /usr/bin/salt --static --out=json
192.168.1.100 service.status nginx` from a shell on the machine
running salmon, what happens?

**Comment by frankV** [comment]
Seems like salt times out. Here's the traceback.

``` python
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/lib/pymodules/python2.7/salt/scripts.py", line 103, in salt_main
    client.run()
  File "/usr/lib/pymodules/python2.7/salt/cli/__init__.py", line 104, in run
    full_ret = local.cmd_full_return(**kwargs)
  File "/usr/lib/pymodules/python2.7/salt/client.py", line 476, in cmd_full_return
    **kwargs)
  File "/usr/lib/pymodules/python2.7/salt/client.py", line 213, in run_job
    **kwargs)
  File "/usr/lib/pymodules/python2.7/salt/client.py", line 1088, in pub
    payload = sreq.send('clear', payload_kwargs)
  File "/usr/lib/pymodules/python2.7/salt/payload.py", line 185, in send
    timeout * tried
salt.exceptions.SaltReqTimeoutError: Waited 60 seconds
```

**Comment by ipmb** [comment]
It sounds like you don't have salt-minion running and connected on the
target. Have you gone through the steps here?
http://salt.readthedocs.org/en/latest/topics/configuration.html

**Comment by frankV** [comment]
It did turn out to be an issue with my salt-minion. I had to remove and reinstall it. Thanks for your help Peter. I got it working but have an `AttributeError` with `percentage_with_sign`. I'll give it the old college try though. Thanks again.
